"""InterviewQuestion database model.

Stores AI-generated interview questions tied to a resume analysis.
Each row represents a single question produced by the Interview
Question Generator Agent.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, DateTime, ForeignKey, JSON

from backend.app.core.database import Base


class InterviewQuestion(Base):
    """A single interview question generated by the AI agent.

    Attributes:
        id: UUID primary key.
        user_id: FK to the owning user.
        resume_analysis_id: FK to the ADK resume analysis used as context.
        company: Target company for the question.
        role: Target role for the question.
        interview_type: Overall interview type (HR, Technical, Coding, Mixed).
        difficulty: Difficulty level (Easy, Medium, Hard).
        question_type: Specific question category (HR, Technical, Coding, etc.).
        question: The interview question text.
        expected_answer: Expected or ideal answer.
        hints: JSON list of hints for the candidate.
        follow_up: Optional follow-up question.
        tags: JSON list of keyword tags.
        created_at: UTC timestamp of when the question was generated.
    """

    __tablename__ = "interview_questions"

    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    user_id = Column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    resume_analysis_id = Column(
        String(36),
        ForeignKey("resume_analyses_adk.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    company = Column(
        String(255),
        nullable=False,
    )
    role = Column(
        String(255),
        nullable=False,
    )
    interview_type = Column(
        String(50),
        nullable=False,
    )
    difficulty = Column(
        String(20),
        nullable=False,
    )
    question_type = Column(
        String(50),
        nullable=False,
    )
    question = Column(
        Text,
        nullable=False,
    )
    expected_answer = Column(
        Text,
        nullable=True,
    )
    hints = Column(
        JSON,
        nullable=True,
    )
    follow_up = Column(
        Text,
        nullable=True,
    )
    tags = Column(
        JSON,
        nullable=True,
    )
    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
    )

    def __repr__(self) -> str:
        return (
            f"<InterviewQuestion(id={self.id}, type={self.question_type}, "
            f"difficulty={self.difficulty})>"
        )
