import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, DateTime, Integer, Text, ForeignKey
from sqlalchemy.orm import relationship
from backend.app.core.database import Base


class StudyPlan(Base):
    """Individual day entry in a personalised study plan.

    The study plan is generated by the AI agent based on the candidate's
    weak topics. Each row represents one day's task. The `day` field
    indicates sequence order (day 1, day 2, …). Status tracks completion.

    Relationships:
        user: The candidate following this plan.
    """
    __tablename__ = "study_plans"

    id = Column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
    )
    user_id = Column(
        String(36),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    day = Column(
        Integer,
        nullable=False,
        comment="Day number within the plan sequence (1-based)",
    )
    topic = Column(
        String(255),
        nullable=False,
        comment="High-level subject, e.g. 'Python OOP' or 'System Design'",
    )
    task = Column(
        Text,
        nullable=False,
        comment="Concrete task description, e.g. 'Implement a decorator'",
    )
    status = Column(
        String(20),
        default="pending",
        comment="Completion state: 'pending', 'in_progress', 'completed'",
    )
    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
    )

    user = relationship("User", back_populates="study_plans")

    def __repr__(self) -> str:
        return f"<StudyPlan(id={self.id}, day={self.day}, topic={self.topic})>"
