"""Pydantic schemas for the Interview Question Generator Agent.

Three layers of schema:
1. ``InterviewQuestionItem`` — a single question in the Gemini response.
2. ``InterviewQuestionList`` — top-level schema that Gemini is instructed
   to return. This is passed as ``output_schema`` to the ADK Agent.
3. ``InterviewQuestionCreate`` / ``InterviewQuestionResponse`` — database
   persistence schemas following the project convention.
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# ADK Agent output schemas (Gemini response_schema)
# ---------------------------------------------------------------------------


class InterviewQuestionItem(BaseModel):
    """A single interview question generated by the AI agent.

    This schema is used both as part of the Gemini response and as the
    building block for database persistence.
    """

    type: str = Field(
        ...,
        description=(
            "Question type — one of: HR, Technical, Coding, Behavioral, "
            "Resume, System Design, Project Discussion"
        ),
    )
    question: str = Field(
        ..., description="The interview question text"
    )
    expected_answer: str = Field(
        ..., description="Expected or ideal answer to the question"
    )
    hints: List[str] = Field(
        default_factory=list,
        description="List of hints to help the candidate answer",
    )
    follow_up: str = Field(
        "",
        description="Optional follow-up question that probes deeper",
    )
    tags: List[str] = Field(
        default_factory=list,
        description="Keyword tags for categorisation (e.g. python, ml, leadership)",
    )


class InterviewQuestionList(BaseModel):
    """Top-level Gemini response containing all generated questions.

    This schema is used as the ADK Agent's ``output_schema`` so that
    Gemini 2.5 Flash returns strictly typed JSON matching these fields.
    """

    questions: List[InterviewQuestionItem] = Field(
        ..., description="List of generated interview questions"
    )


# ---------------------------------------------------------------------------
# Request schema
# ---------------------------------------------------------------------------


class InterviewQuestionGenerateRequest(BaseModel):
    """Request body for triggering question generation."""

    resume_analysis_id: str = Field(
        ...,
        description="ID of the ADK resume analysis to base questions on",
    )
    company: str = Field(
        ..., max_length=255, description="Target company for the interview"
    )
    role: str = Field(
        ...,
        max_length=255,
        description="Target role / job title for the interview",
    )
    interview_type: str = Field(
        ...,
        description="Interview type: HR, Technical, Coding, or Mixed",
    )
    difficulty: str = Field(
        ...,
        description="Difficulty level: Easy, Medium, or Hard",
    )
    number_of_questions: int = Field(
        10,
        ge=1,
        le=50,
        description="Number of questions to generate (1–50)",
    )


# ---------------------------------------------------------------------------
# CRUD schemas (follow existing project convention)
# ---------------------------------------------------------------------------


class InterviewQuestionBase(BaseModel):
    """Shared fields for interview question records."""

    resume_analysis_id: str = Field(
        ..., description="FK to the ADK resume analysis"
    )
    company: str = Field(..., max_length=255)
    role: str = Field(..., max_length=255)
    interview_type: str = Field(..., max_length=50)
    difficulty: str = Field(..., max_length=20)
    question_type: str = Field(..., max_length=50)
    question: str = Field(...)
    expected_answer: Optional[str] = None
    hints: Optional[List[str]] = None
    follow_up: Optional[str] = None
    tags: Optional[List[str]] = None


class InterviewQuestionCreate(InterviewQuestionBase):
    """Schema for creating a new interview question record."""

    user_id: str


class InterviewQuestionUpdate(BaseModel):
    """Schema for updating an existing interview question record.

    All fields are optional — only provided fields will be patched.
    """

    expected_answer: Optional[str] = None
    hints: Optional[List[str]] = None
    follow_up: Optional[str] = None
    tags: Optional[List[str]] = None


class InterviewQuestionResponse(InterviewQuestionBase):
    """Schema for interview question data returned to API clients."""

    id: str
    user_id: str
    created_at: datetime

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# Response wrapper for the generate endpoint
# ---------------------------------------------------------------------------


class InterviewQuestionGenerateResponse(BaseModel):
    """Wrapper response for the question generation endpoint."""

    questions: List[InterviewQuestionResponse] = Field(
        ..., description="Generated interview questions"
    )
